### ISSUE TITLE
Issue with GOST IP addresses

### ISSUE THREAD

**Issue by LucaMannella** [gost/docker-compose#5]
Hi guys,

as you can see in the picture below, when I try to use the docker-compose-0.5.yml to create my local GOST instance there is a missing slash between the address and the version number.

![gost_issue](https://user-images.githubusercontent.com/9093937/68132631-4fd5ee00-ff1f-11e9-95ba-efd7c9fc9633.PNG)

In this way, it is impossible to write a software that take advantage of the fields "@iot.navigationLink" (that could be useful to navigate through related entities).

![gost_issue_2](https://user-images.githubusercontent.com/9093937/68132939-d25ead80-ff1f-11e9-95e7-06cf19840340.PNG)

Furthermore, I would expect to have a "localhost" address instead of the Docker private one. Do you know how to get a directly usable URL?

Thanks in advance for your help.
Luca

**Comment by bertt** [comment]
Hi Luca, can you try using docker-compose.yml instead of  docker-compose-0.5.yml? Please note there is also an environmental variable for setting the external uri 'GOST_SERVER_EXTERNAL_URI'

**Comment by LucaMannella** [comment]
Hi Bert, thanks for your support!
I tryed using "docker-compose.yml" and it seems that this issue is solved.
Could I use this version of GOST considering it as stable?

**Comment by bertt** [comment]
ok good its working now, this was a known issue in 0.5 release. You can use  this latest version as stable.
